### ISSUE TITLE
Implement Art Assets

### ISSUE THREAD

**Issue by Labrasones** [NikVidya/Siege-Engineer#10]
- [x] Player Animation
- [x] Resource Sprites
- [x] Tilemap

**Comment by Labrasones** [comment]
@alsiushaku I've accidentally deleted the steel resource sprite on the Google Drive (damn button is right under download in the context menu, and the undo just spat out an error 😞)
If you still have a copy of that file, please re-upload it

**Comment by alsiushaku** [comment]
@Labrasones uploaded!!
