### ISSUE TITLE
Damageables repair on damage tick

### ISSUE THREAD

**Issue by Labrasones** [NikVidya/Siege-Engineer#17]
With the current implementation, damageables will only be healed during the healthDecreaseRate timer tick. This can lead to problems for the strategy of over time healing.

Specifically, if the amount of time the Damageable should be healing for is smaller than the healthDecreaseRate, it will not receive healing due to the first tick coming later than the heal time. I recommend we either move away from InvokeRepeating, or create separate ticks for healing and damage.

Alternatively, the repair system could be set up to do a flat amount of repair in the instant that it's invoked.

**Comment by nmasdev** [comment]
I agree that it shouldn't be limited to the timing of the damage tick. We'll have to talk about how we want the gate to be damaged in the meeting today
