### ISSUE TITLE
Currency spawning

### ISSUE THREAD

**Issue by nmasdev** [NikVidya/Siege-Engineer#28]
currency items should spawn every few seconds (test for frequency) within the game area. Player picks them up by moving within proximity.
Need art assets for currency world item/ui (shiny looking shrapnel)
Need UI number to indicate currency (bottom right for now)

**Comment by Labrasones** [comment]
This seems to have been closed by pull request #35. However, some art is going to be implemented by #40. We may also need to revisit the HUD design to make it easier to determine how my currency the player has.
