### ISSUE TITLE
Wave system

### ISSUE THREAD

**Issue by nmasdev** [NikVidya/Siege-Engineer#33]
UI to indicate when the structures are taking damage, timers to indicate wave/rest duration
code to let structures know when the wave is going

**Comment by Labrasones** [comment]
So, I thought of something else I wanted to mention about the wave system design.

If you do go the route I was talking about after class on Thursday, make a rest wave a specific kind of wave.

So the idea is that each wave is a distinct serialized object. Like a game object or a prefab or whatever. And that game object stores things like damage, length, stuff like that. So the rest wave would be a type of wave that has no damage. That way it can be put in the level wave queue just like any other wave.

That'll make it much easier to set up patterns of waves and stuff per level. Like, one level could have three different styles of attack wave in a row, where as another level might have alternating patterns of attack and rest.
